name: Build and Push Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:  
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set DOCKER_DEFAULT_PLATFORM
        run: echo "DOCKER_DEFAULT_PLATFORM=linux/arm64" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t telegram-bot-api-builder:latest .
          docker create --name bot-builder telegram-bot-api-builder:latest
          docker cp bot-builder:/output/telegram-bot-api-aarch64 ./telegram-bot-api-aarch64
          docker rm bot-builder

      - name: Commit and push the binary
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./telegram-bot-api-aarch64
          git commit -m "Add built binary file"
          git push
